### PR TITLE
Add codecov upload

### PR DESCRIPTION
**Pull request by Licenser**

### CODE REVIEW

**Comment by sunnygleason** [comment]
nice! I was working on this but running into issues... very cool if/when it works!

**Comment by Licenser** [comment]
let see :joy:

**Comment by sunnygleason** [comment]
@Licenser wow, is this all set?

**Comment by sunnygleason** [comment]
@Licenser oh! I just remembered one thing I was going to request/suggest -- maybe do the clippy changes as a preceding PR so this one is just build system related? I started reviewing this and then had my mind blown... 💥

**Comment by Licenser** [comment]
Ja, will do that with the next PR, I somewhat dind't expect that to explode like that when I started then it was all over :joy: and I just found out that this isn't even doing all the clippy stuff but I'll dot he rest in a 2nd PR

**Comment by Licenser** [comment]
I got the next set of changes (more clippy fixes + docs for the public interface) stashed so I can drop it in a new branch once this is merged - I didn't wanted to throw those in ontop.

**Comment by sunnygleason** [comment]
@Licenser could we sneak those stashed changes in *before* this PR? Are these the ones required for CI cleanliness?

If we take these 2 commits away, this PR is much smaller no?

* 602f9d7228e9c22e1ed73e5d732b39af8329a623
* 7692255b52d2858d5d850f691f2af1d763fb46c3

**Comment by Licenser** [comment]
Ja I'll cherry pick them on master, I checked it'll not cause rebase issues

**Comment by Licenser** [comment]
done!

**Pull request merged**
