### PR TITLE
128 bit numbers

### PR DESCRIPTION
**Pull request by Licenser**
See #59 

todo:
- [x] bench
- [x] implement 128bit parsing
- [x] remove 128bit as default flag

### CODE REVIEW

**Comment by Licenser** [comment]
Initial perf (just memory layout updates & functions, no parsing).

Impact is measurable but not terrible, nothing to enable by default but as a flag for those who need it it's acceptable performance I think.

## 0.2.2 (master)
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         530 MB/s   420 MB/s   710 MB/s   320 MB/s
data/citm_catalog.json  1130 MB/s   480 MB/s  1550 MB/s   610 MB/s
data/twitter.json        920 MB/s   600 MB/s  1000 MB/s   640 MB/s
data/log.json           1080 MB/s  1080 MB/s  1080 MB/s  1080 MB/s

===== simd_json_tape ===== parse|stringify ===== parse|stringify ====
data/canada.json         770 MB/s
data/citm_catalog.json  1890 MB/s
data/twitter.json       1670 MB/s
data/log.json           2170 MB/s
```

## this
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         510 MB/s   430 MB/s   670 MB/s   330 MB/s
data/citm_catalog.json  1110 MB/s   500 MB/s  1520 MB/s   650 MB/s
data/twitter.json        900 MB/s   610 MB/s   970 MB/s   650 MB/s
data/log.json           1080 MB/s  1080 MB/s  1080 MB/s  1080 MB/s

===== simd_json_tape ===== parse|stringify ===== parse|stringify ====
data/canada.json         760 MB/s
data/citm_catalog.json  1880 MB/s
data/twitter.json       1640 MB/s
data/log.json           2170 MB/s
```

image

**Comment by Licenser** [comment]
@mstump do you want to give this branch a try and see if it solves your issue?

**Comment by Licenser** [comment]
(marking this as non draft to get codecov to post it's stuff) - not ready to be merged yet but input is more then welcome

**Comment by Licenser** [comment]
image
 :joy: well no this definetly needs work!

**Comment by Licenser** [comment]
@sunnygleason this should be ready for review :)

**Comment by Licenser** [comment]
@sunnygleason could I bug you for a review so we can merge this?

**Comment by mstump** [comment]
I finally climbed out from under my pile of demos and I'm sorry to report that I'm still getting weird behavior with this branch. 

Cargo snipit:
```
[dependencies.simd-json]
git = "https://github.com/simd-lite/simdjson-rs"
branch = "128-bit-numbers"
features = ["128bit"]
```

With the 128bit feature enabled I get the error message:
```
thread 'reporter_message::raw_message::tests::test_deserialize_elastic_search' panicked at 'JsonSimdError(Error { index: 0, character: '💩', error: Serde("invalid type: i128, expected any value") })', src/reporter_message/raw_message.rs:398:25
```

Where previously I got:
```
thread 'reporter_message::raw_message::tests::test_deserialize_elastic_search' panicked at 'JsonSimdError(Error { index: 191048, character: '\n', error: Overflow })', src/reporter_message/raw_message.rs:398:25
```

The enum that it's decoding is
```
#[serde(untagged)]
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum RawMessageMetricValue {
    Boolean(bool),
    Float(f64),
    Long(i128),
    Integer(i64),
    Metric(Vec<RawMessageMetricNode>),
    String(String),
}
```

The offending JSON is below, it cleanly deserializes with `serde_json`.
```
{
  "name": "max_unsafe_auto_id_timestamp",
  "value": -9223372036854776000
}
```

**Comment by Licenser** [comment]
That looks like I did something wrong in the serde interop, I’ll check tomorrow if I can work out what serde expects of us for 128 but support thanks for sharing the structure and data that go right into a test

Cheers,
Heinz
________________________________

**Comment by Licenser** [comment]
Turns out this is a bug in serde, it doesn't support untagged fields with 128 bit values :/ 

https://github.com/serde-rs/serde/blob/ff70409215b62fa8cd138ce47534c432352c85bb/serde/src/private/de.rs#L230

**Comment by sunnygleason** [comment]
@Licenser what should the next step for this PR be?

**Comment by Licenser** [comment]
I opened a ticket with serde: https://github.com/serde-rs/serde/issues/1717

I'm honestly not 100% sure, merging it would already allow 128 bit values outside of enums and should work there once it is fixed in serde.

Since no code changes will be required I think we could still merge it, there is little reason to hold it back just because of a bug in serde.

other then that clippy is throwing spanners in the works :P only 177 new errors! yay

**Comment by sunnygleason** [comment]
@Licenser sure! Were you able to run fuzz testing for the feature? Just curious...

**Comment by Licenser** [comment]
I haven't it has been broken for a bit, and it feels with #95 in the todo list it's not worth investing time into unbreak it. We'll scrap the current fuzz stuff anyway.

**Pull request merged**
