### PR TITLE
feat: improve utf8 modularity w/ Utf8Check trait

### PR DESCRIPTION
**Pull request by sunnygleason**
* improve Utf8 modularity w/ trait
* align [sse42, avx2, neon] to upstream version(s) 0.2.1
* [x] stage1
* [x] utf8check
* [ ] number parse (do later in future PR)
* [ ] string parse (do later in future PR)

TODO:

* benchmark to ensure no adverse effects

### CODE REVIEW

**Comment by sunnygleason** [comment]
@Licenser I think this is worth a look -- thank you for your feedback!

* if you could pay close attention to the rust annotations, that would be super helpful
* I'm surprised by the codecov drops, I'm assuming it's from annotations

With these changes, I think we're getting pretty close to upstream 0.2.x alignment which is cool.

* Hopefully the benchmarks are still friendly!

**Comment by Licenser** [comment]
Code wise the change looks perfect and killing off another 40 lines is awesome :D - I think the clippy issues are quick to fix. That said I find a 1.29% drop in code coverage a bit hefty can you try to bring that a bit closer to +/- 0?

**Comment by sunnygleason** [comment]
@Licenser yes, I'm puzzled by the code coverage dropoff - it looks like something weird is going on:

image

Maybe I should hoist those bytes into an inline function outside the trait?

**Comment by Licenser** [comment]
What I noticed is that some of the multi line `assert!`'s are marked as not covered, a simple way to gain back a few % would be moving

```rust
assert!(
some_long_function_that_does_stuff(),
A::Very(Long::Value(That::Is("nested))
);
```

to

```rust
let exp = some_long_function_that_does_stuff();
let got = A::Very(Long::Value(That::Is("nested));
assert!(exp, got);
```

and yes pulling out some of the lengthy consts might be nice - it'll probably increase readability as well

**Comment by Licenser** [comment]
Perf wise it looks good :D

## 0.2
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         530 MB/s   420 MB/s   710 MB/s   330 MB/s
data/citm_catalog.json  1110 MB/s   480 MB/s  1550 MB/s   600 MB/s
data/twitter.json        920 MB/s   610 MB/s  1000 MB/s   650 MB/s
data/log.json           1080 MB/s  1080 MB/s  1080 MB/s  1080 MB/s

===== simd_json_tape ===== parse|stringify ===== parse|stringify ====
data/canada.json         770 MB/s
data/citm_catalog.json  1900 MB/s
data/twitter.json       1670 MB/s
data/log.json           2170 MB/s
```

## this
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         530 MB/s   420 MB/s   710 MB/s   330 MB/s
data/citm_catalog.json  1130 MB/s   480 MB/s  1550 MB/s   600 MB/s
data/twitter.json        910 MB/s   600 MB/s   990 MB/s   640 MB/s
data/log.json           1080 MB/s  1080 MB/s  1080 MB/s  1080 MB/s

===== simd_json_tape ===== parse|stringify ===== parse|stringify ====
data/canada.json         770 MB/s
data/citm_catalog.json  1900 MB/s
data/twitter.json       1650 MB/s
data/log.json           2170 MB/s
```

image

**Comment by Licenser** [comment]
Holy cow! You did it :D

**Comment by sunnygleason** [comment]
> Holy cow! You did it :D

Does this look merge-worthy? Let me know if there's anything else I can do!

**Comment by Licenser** [comment]
Absolutely! +1. Thanks for going through it and catching up with upstream:)

**Pull request merged**
